### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Artyom16RUS** [Artyom16RUS/JdbcTemplate-advanced#1]
Не уверен, правильно ли я понял домашнее задание. Вместо _Statement_ сделать _PreparedStatement_

**Comment by coursar** [comment]
Нет, надо было добавить возможность выполнять запросы через PreparedStatement в JdbcTemplate. Мы это уже сделали - у вас был шаблон на лекциях, поэтому сдавать это ДЗ не нужно
